### ISSUE TITLE
[BUG] Desktop lyrics plugin is not always on top/hidden by other applications

### ISSUE THREAD

**Issue by bigplayer-ai** [lx200916/desktop_lyrics_plugin#15]
Hey,
Desktop lyrics plugin is hidden (not always on top) when openning other applications as shown in the image below:
![Clip_20230208_163855](https://user-images.githubusercontent.com/119108387/217561260-7bc3a53b-00c2-46a6-882c-c6fada3e4464.png)
![Clip_20230208_163902](https://user-images.githubusercontent.com/119108387/217561300-af61eff7-9849-4fb4-84bb-e481328e5535.png)

**Comment by lx200916** [comment]
U mean All apps or only `some` apps? Because it indeed works on my Win10 22H2.
P.S. In fact we can not `keep one window always on the top` on Windows, this plugin set its window `HWND_TOPMOST` but it can be overriden by some system windows (TaskMgr etc..) or any other user apps set themselves to `TOPMOST`.
One possible way is to set `TOPMOST` from time to time but it can consume  lots of CPU and help little (Others may keep setting themselves too).

**Comment by bigplayer-ai** [comment]
Ok keep it this waySent from Yazan’s iPadOn 9 Feb 2023, at 10:03, Lee ***@***.***> wrote:﻿
U mean All apps or only some apps? Cause it indeed works on my Win10 22H2.
P.S. In fact we can not keep one window always on the top on Windows, this plugin set its window HWND_TOPMOST but it can be override by some system windows (TaskMgr etc..) or any other user apps set themselves to TOPMOST.
One possible way is to set TOPMOST from time to time but it can consume  lots of CPU and help little (Others may keep setting themselves too).
