### ISSUE TITLE
Feature request: is there a way to change the size/background of the lyrics? Or to have it display w/ screensaver on?

### ISSUE THREAD

**Issue by Manchovies** [lx200916/desktop_lyrics_plugin#9]
First off, thanks for doing this! Looks like the only MiniLyrics alternative that works with Cider. Is anything I mentioned in the title possible?

**Comment by lx200916** [comment]
Hi, I may check if we can add something to change the Background Color things.

But the font size( You mean font size of the lyrics right?) may be tough( imagining that if there's a looong line of lyrics and it might overflow the width of the desktop, we need to consider line-break or some tricks... a LARGER font size can make those tough scenarios more likely to happen).

**Comment by lx200916** [comment]
BTW, I dont get what ` have it display w/ screensaver on` means...

**Comment by Manchovies** [comment]
Hey, thanks for your response!
I'm wondering if there's a way to have the lyrics display on top of my
screensaver on my PC.
I have Wallpaper Engine installed, which works pretty well and just like
most Windows screensavers. I'm wondering if I could have my screensaver
going on my computer, and have the lyrics from your plugin show "over" the
screensaver.

**Comment by lx200916** [comment]
Okay I got it. If you mean `Displaying a Lyrics Window on a Desktop WALLPAPER powered by  Wallpaper Engine `,it functions well now already. But if you want to `Display something on Windows ScreenSaver`(no matter powered by WE or other sources), I think it may hard to realize since ScreenSaver is always controlled by Windows itself and no window is support to render `over` it.So...I am afraid this feature may not  be added.

But I will look into the BG color things  😆

**Comment by lx200916** [comment]
Fixed. Update the plugin and see README here:[config file ](https://github.com/lx200916/desktop_plugin_server)
